# Generated by Django 2.2.12 on 2020-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('R', 'Reader'), ('A', 'Author')], default='R', max_length=1),
        ),
    ]
